version: '3'
services:
  mariadb:
    build:
      context: .
      dockerfile: ./mariadb/dockerfile
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork

  wordpress:
    build:
      context: .
      dockerfile: ./wordpress/dockerfile
    restart: always
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    restart: always
    ports:
      - 443:443
    networks:
      - mynetwork

volumes:
  mariadb_data:
   driver: local
   driver_opts:
    type: none
    device: /home/eradi-/data/mariadb
    o: bind
  wordpress_data:
   driver: local
   driver_opts:
    type: none
    device: /home/eradi-/data/wordpress
    o: bind
networks:
  mynetwork:
