# FROM debian:buster

# # Install required packages


# RUN apt-get update && apt-get install -y \
#     mariadb-server \
#     php7.3 \
#     php7.3-fpm \
#     curl \
#     php7.3-mysql \
#     && rm -rf /var/lib/apt/lists/*

# RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

# RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# COPY ./wordpress/script.sh /script.sh
# COPY ./wordpress/www.conf /etc/php/7.3/fpm/pool.d/www.conf
# COPY ./wordpress/wp-config.php /var/www/html/wp-config.php
# RUN chmod +x /script.sh
# RUN sh /script.sh

# # Start PHP-FPM service
# CMD ["php-fpm7.3", "--nodaemonize", "--allow-to-run-as-root"]

FROM debian:buster
RUN mkdir -p /var/www/html/wordpress 
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y curl \
	php \
	php-fpm \
	php-mysql \
	php-mysqli \
	mariadb-client \
 	&& curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp
EXPOSE 9000
COPY /tools/my_entrypoint.sh /var/www/html/wordpress
COPY /tools/www.conf /etc/php/7.3/fpm/pool.d/www.conf
CMD ["sh", "/var/www/html/wordpress/my_entrypoint.sh" ]
