FROM debian:buster
RUN apt-get update && apt-get install -y nginx
EXPOSE 443
COPY nginx.conf /etc/nginx/conf.d/
COPY index.html /var/www/html/wordpress/
COPY certificate.crt /etc/ssl/
COPY private.key /etc/ssl/
CMD ["nginx", "-g", "daemon off;"]