FROM debian:buster
RUN apt-get update && apt-get install -y nginx
EXPOSE 443
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/index.html /usr/share/nginx/html
COPY ./nginx/certificate.crt /etc/ssl/
COPY ./nginx/private.key /etc/ssl/
CMD ["nginx", "-g", "daemon off;"]
