# FROM debian:buster
# RUN apt-get update && apt-get install -y php7.3 \
# php7.3-fpm php7.3-mysql mariadb-client \
# nginx curl
# RUN curl -O ./wp-cli.phar
# RUN chmod +x ./wp-cli.phar && mv ./wp-cli.phar /usr/local/bin/wp
# COPY ./script.sh /script.sh
# COPY ./wordpress.conf /etc/php/7.3/fpm/pool.d/
# RUN chmod +x script.sh
# RUN mkdir /run/php/
# ENTRYPOINT ["sh", "script.sh"]
# CMD ["php-fpm7.3", "-R", "-F"]

FROM debian:buster
RUN apt-get update && \
    apt-get install -y php7.3 php7.3-mysql wget && \
    rm -rf /var/lib/apt/lists/*
RUN wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz && \
    tar -C /var/www/html/ -xzf /tmp/wordpress.tar.gz --strip-components=1 && \
    rm /tmp/wordpress.tar.gz
COPY wp-config.php /var/www/html/
COPY script.sh /usr/local/bin/script.sh
RUN chmod +x /usr/local/bin/script.sh
RUN /usr/local/bin/script.sh
CMD tail -f
