FROM debian:buster
RUN apt-get update && \
    apt-get install -y mariadb-server && \
    rm -rf /var/lib/apt/lists/*

COPY ./mariadb/mysql.conf /etc/mysql/mariadb.conf.d/

ENV MYSQL_ROOT_PASSWORD=mehdidb@123
ENV MYSQL_ADMIN_USER=eradi-
ENV MYSQL_ADMIN_PASSWORD=eradidb@123

# Start MySQL server, create databases, and grant permissions
RUN /etc/init.d/mysql start && \
    mysql -u root -peradidb@123 -e "CREATE DATABASE mydb;" && \
    mysql -u root -peradidb@123 -e "CREATE USER '${eradi-}'@'%' IDENTIFIED BY '${eradi-db@123}';" && \
    mysql -u root -peradidb@123 -e "GRANT ALL PRIVILEGES ON *.* TO '${eradi-}'@'%' WITH GRANT OPTION;" && \
    mysql -u root -peradidb@123 -e "FLUSH PRIVILEGES;" && \
    /etc/init.d/mysql stop

# Expose the MySQL port
EXPOSE 3306

# Start MySQL server when container is started
CMD ["mysqld"]